---
kind: pipeline
name: default

steps:
- name: Build Opencensus Sidecar
  image: drone-docker
  commands:
    - apt-get update
    - apt-get install make
    - make censusai-build-docker
    - make censusai-push-docker
  when:
    branch:
      - master
    event:
      - push
      - pull_request
- name: Helm Lint
  image: lachlanevenson/k8s-helm:v2.13.1
  commands:
    - helm lint ./chart
  when:
    branch:
      - master
    event:
      - push
      - pull_request

