---
kind: pipeline
name: default

steps:
- name: Build Flanders
  image: golang:1.12
  commands:
  - go build -o /usr/local/bin/flanders ./cmd/flanders
  environment:
    GOPROXY: "https://athens.azurefd.net"
    PATH: "/usr/local/bin:${PATH}"
  volumes:
  - name: localbin
    path: /usr/local/bin
- name: Build and Push The CensusAI Sidecar
  image: golang:1.12
  commands:
  - flanders censusai build
  - docker login quay.io -u ${QUAY_ROBOT_USERNAME} -p ${QUAY_ROBOT_PASSWORD}
  - flanders censusai push
  environment:
    PATH: "/usr/local/bin:${PATH}"
    CENSUSAI_IMAGE: "quay.io/arschles/censusai-forwarder"
    QUAY_ROBOT_USERNAME:
      from_secret: quay_robot_username
    QUAY_ROBOT_PASSWORD:
      from_secret: quay_robot_password
  when:
    branch:
    - master
  volumes:
    - name: localbin
      path: /usr/local/bin
- name: Helm Lint The Athens Chart
  image: lachlanevenson/k8s-helm
  commands:
  - helm lint ./charts/athens
