---
kind: pipeline
name: default

steps:
- name: Build Flanders
  image: golang:1.12
  commands:
  - go build -o flanders ./cmd/flanders
  - go install -o flanders ./cmd/flanders
- name: Build and Push The CensusAI Sidecar
  image: golang:1.12
  commands:
  - flanders censusai build
  - docker login quay.io -u ${QUAY_ROBOT_USERNAME} -p ${QUAY_ROBOT_PASSWORD}
  - flanders censusai push
  environment:
    CENSUSAI_IMAGE: "quay.io/arschles/censusai-forwarder"
    QUAY_ROBOT_USERNAME:
      from_secret: quay_robot_username
    QUAY_ROBOT_PASSWORD:
      from_secret: quay_robot_password
  when:
    branch:
    - master
