---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Build Flanders
  image: golang:1.12
  commands:
  - go build -o /usr/local/bin/flanders ./cmd/flanders
  environment:
    GOPROXY: https://athens.azurefd.net
  volumes:
  - name: localbin
    path: /usr/local/bin

- name: Build and Push The CensusAI Sidecar
  image: golang:1.12
  commands:
  - flanders censusai build
  - "docker login quay.io -u ${QUAY_ROBOT_USERNAME} -p ${QUAY_ROBOT_PASSWORD}"
  - /usr/local/bin/flanders censusai push
  environment:
    CENSUSAI_IMAGE: quay.io/arschles/censusai-forwarder
    QUAY_ROBOT_PASSWORD:
      from_secret: quay_robot_password
    QUAY_ROBOT_USERNAME:
      from_secret: quay_robot_username
  volumes:
  - name: localbin
    path: /usr/local/bin
  when:
    branch:
    - master

- name: Helm Lint The Athens Chart
  image: lachlanevenson/k8s-helm
  commands:
  - helm lint ./charts/athens

...
