---
kind: pipeline
name: default

steps:
- name: Build Opencensus Sidecar
  image: plugins/docker
  commands:
    - make censusai-build-docker
    - makecensusai-push-docker
  when:
    branch:
      - master
    event:
      - push
      - pull_request
- name: Helm Lint
  image: lachlanevenson/k8s-helm:v2.13.1
  commands:
    - helm lint ./chart
  when:
    branch:
      - master
    event:
      - push
      - pull_request

