---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Build Flanders
  image: golang:1.12
  commands:
  - go build -o /usr/local/bin/flanders ./cmd/flanders
  volumes:
  - name: localbin
    path: /usr/local/bin
  environment:
  GOPROXY: https://athens.azurefd.net

...
