ARG GOLANG_VERSION=1.13
FROM golang:${GOLANG_VERSION}-alpine AS builder

WORKDIR /lathens

COPY . .

RUN GO111MODULE=on CGO_ENABLED=0 GOPROXY="https://proxy.golang.org" go build -o /bin/lathens ./lathens

FROM alpine

ENV GO111MODULE=on

COPY --from=builder /bin/lathens /bin/lathens

RUN apk add --update openssh-client subversion procps fossil

EXPOSE 3000

CMD ["lathens"]
