ARG GOLANG_VERSION=1.13
FROM golang:${GOLANG_VERSION}-alpine AS builder

WORKDIR /crathens

COPY . .

RUN GO111MODULE=on CGO_ENABLED=0 GOPROXY="https://proxy.golang.org" go build -o /bin/crathens ./crathens

FROM alpine

ENV GO111MODULE=on

COPY --from=builder /bin/crathens /bin/crathens

RUN apk add --update openssh-client subversion procps fossil

EXPOSE 3000

CMD ["crathens"]
