AZURE_ATHENS_RESOURCE_GROUP ?= athens
AZURE_ATHENS_CONTAINER_NAME ?= athens
IMAGE_TAG ?= v0.3.0
AZURE_ATHENS_DNS_NAME ?= athens

deploy:
	AZURE_ATHENS_RESOURCE_GROUP=${AZURE_ATHENS_RESOURCE_GROUP} \
	AZURE_ATHENS_CONTAINER_NAME=${AZURE_ATHENS_CONTAINER_NAME} \
	AZURE_ATHENS_CONTAINER_NAME=${AZURE_ATHENS_CONTAINER_NAME} \
	IMAGE_TAG=${IMAGE_TAG} \
	AZURE_ATHENS_DNS_NAME=${AZURE_ATHENS_DNS_NAME} \
	./aci.sh

build-flanders:
	go build -o flanders ./cmd/flanders

install-flanders:
	go install ./cmd/flanders
