AZURE_ATHENS_RESOURCE_GROUP ?= athens
AZURE_ATHENS_CONTAINER_NAME ?= athens
IMAGE_TAG ?= v0.3.0
AZURE_ATHENS_DNS_NAME ?= athens

deploy:
	AZURE_ATHENS_RESOURCE_GROUP=${AZURE_ATHENS_RESOURCE_GROUP} \
	AZURE_ATHENS_CONTAINER_NAME=${AZURE_ATHENS_CONTAINER_NAME} \
	AZURE_ATHENS_CONTAINER_NAME=${AZURE_ATHENS_CONTAINER_NAME} \
	IMAGE_TAG=${IMAGE_TAG} \
	AZURE_ATHENS_DNS_NAME=${AZURE_ATHENS_DNS_NAME} \
	./aci.sh

CENSUSAI_IMAGE_TAG ?= canary
CENSUSAI_IMAGE ?= arschles/censusai-forwarder:${CENSUSAI_IMAGE_TAG}


censusai-build-docker:
	docker build -t ${CENSUSAI_IMAGE} ./census

censusai-local-docker:
	docker run \
		-d -p 55678:55678 \
		-e APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY} \
		${CENSUSAI_IMAGE} \
		./census


