name: OpenCensus to App Insights Forwarder
on: [push]

jobs:

  build:
    name: build & push opencensus to app insights forwarder
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    # TODO: fix the build/push
    # - name: Build & push forwarder
    #   run: |
    #     echo ${DOCKER_HUB_PASSWORD} | docker login --username=${DOCKER_HUB_USERNAME} --password-stdin
    #     make census-docker-push
    #   env:
    #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
