name: Lathens
on: [push]

jobs:

  build:
    name: Push Lathens docker image
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build and push lathens docker container
      run: |
        # TODO: figure out login
        # docker login --username=${DOCKER_HUB_USERNAME} --password=${DOCKER_HUB_PASSWORD}
        make lathens-docker-build
