name: Terraform
on: [push, pull_request]
jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Terraform RC
      run: echo "$TERRAFORM_RC" > ./.terraformrc
      env:
        TERRAFORM_RC: ${{ secrets.TERRAFORM_RC }}

    
    - name: Terraform init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'tf'
        tf_actions_comment: true
        tf_actions_cli_credentials_token: ./.terraformrc
    
    - name: Format
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: 'tf'
        tf_actions_comment: true
        tf_actions_cli_credentials_token: ./.terraformrc
    
    - name: Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: 'tf'
        tf_actions_comment: true
        tf_actions_cli_credentials_token: ./.terraformrc
      env:
        TF_VAR_kubeconfig-path: tf/kube/config
        TF_VAR_kube-cluster: "flanders"
        TF_VAR_kube-auth: "clusterUser_athens_flanders"

