name: Terraform
on: [push, pull_request]
jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Format
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
